### ISSUE TITLE
Refactoring of android keystore exception handlings for EncryptionManager.

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-android#107]

**Comment by rafaelekol** [comment]
Not handling UserNotAuthenticatedException in app causes app to crash

Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated at android.security.KeyStore.getInvalidKeyException(KeyStore.java:741) at android.security.KeyStore.getInvalidKeyException(KeyStore.java:777) at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54) at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89) at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265) at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:148) at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2659) at javax.crypto.Cipher.tryCombinations(Cipher.java:2570) at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475) at javax.crypto.Cipher.chooseProvider(Cipher.java:566) at javax.crypto.Cipher.init(Cipher.java:973) at javax.crypto.Cipher.init(Cipher.java:908) at bitcoin.wallet.core.security.CipherWrapper.decrypt(CipherWrapper.kt:37) at bitcoin.wallet.core.security.EncryptionManager.decrypt(EncryptionManager.kt:37) at bitcoin.wallet.core.managers.PreferencesManager.getPin(PreferencesManager.kt:56) at bitcoin.wallet.BaseActivity.onResume(BaseActivity.kt:28)
