### ISSUE TITLE
Crash on adding new tokens after fresh restore 

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#1568]
Reproduction: 
Fresh restore BTC account, then immediately add two erc-20 tokens

log:

```
 Process: io.horizontalsystems.bankwallet.dev.master, PID: 17271
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:62 androidx.recyclerview.widget.RecyclerView{76a6327 VFED..... ......ID 0,438-1080,1836 #7f0a01cf app:id/recyclerTransactions}, adapter:io.horizontalsystems.bankwallet.modules.transactions.TransactionsAdapter@1fa189a, layout:io.horizontalsystems.bankwallet.ui.extensions.NpaLinearLayoutManager@c1795cb, context:io.horizontalsystems.bankwallet.modules.main.MainActivity@68e7d97
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:20831)
```

**Comment by tmedetbekov** [comment]
We will return to this issue after implementation of #1494
