### ISSUE TITLE
App crashes on resume, trying to restore fragments

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#1876]
Reproducaction: Open coin chart, and close app. Use RAM filler that will consume RAM, try to open app, and it should crash while trying to restore RateChartFragment

 ```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment io.horizontalsystems.bankwallet.modules.ratechart.RateChartFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2452)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
        at io.horizontalsystems.bankwallet.modules.balance.BalanceFragment.onCreate(BalanceFragment.kt:35)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:270)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1173)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2563)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at io.horizontalsystems.core.CoreActivity.onCreate(CoreActivity.kt:14)
        at io.horizontalsystems.bankwallet.modules.main.MainActivity.onCreate(MainActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
```

**Comment by rafaelekol** [comment]
Same happening with Receive bottom dialog

```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment io.horizontalsystems.bankwallet.modules.receive.ReceiveFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2452)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
        at io.horizontalsystems.bankwallet.modules.balance.BalanceFragment.onCreate(BalanceFragment.kt:35)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:270)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1173)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2563)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at io.horizontalsystems.core.CoreActivity.onCreate(CoreActivity.kt:14)
        at io.horizontalsystems.bankwallet.modules.main.MainActivity.onCreate(MainActivity.kt:39)
```
