### ISSUE TITLE
App crashes on restore on Production

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#2006]
App crashes when user tries to restore 12 words. App reinstall and phone reboot, didn't help.

Crash logs:

```
msg: android.security.KeyStoreException: User authentication required
stacktrace: java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:324)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at io.horizontalsystems.core.security.KeyStoreManager.createKey(KeyStoreManager.kt:89)
	at io.horizontalsystems.core.security.KeyStoreManager.getKey(KeyStoreManager.kt:62)
	at io.horizontalsystems.core.security.EncryptionManager.encrypt(EncryptionManager.kt:12)
	at io.horizontalsystems.bankwallet.core.storage.DatabaseConverters.encryptSecretList(DatabaseConverters.kt:67)
	at io.horizontalsystems.bankwallet.core.storage.AccountsDao_Impl$1.bind(AccountsDao_Impl.java:76)
	at io.horizontalsystems.bankwallet.core.storage.AccountsDao_Impl$1.bind(AccountsDao_Impl.java:41)
	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:63)
	at io.horizontalsystems.bankwallet.core.storage.AccountsDao_Impl.insert(AccountsDao_Impl.java:198)
	at io.horizontalsystems.bankwallet.core.storage.AccountsStorage.save(AccountsStorage.kt:51)
	at io.horizontalsystems.bankwallet.core.managers.AccountManager.save(AccountManager.kt:43)
	at io.horizontalsystems.bankwallet.modules.restore.restorecoins.RestoreCoinsInteractor.create(RestoreCoinsInteractor.kt:40)
	at io.horizontalsystems.bankwallet.modules.restore.restorecoins.RestoreCoinsPresenter.onProceedButtonClick(RestoreCoinsPresenter.kt:38)
	at io.horizontalsystems.bankwallet.modules.restore.restorecoins.RestoreCoinsActivity.onOptionsItemSelected(RestoreCoinsActivity.kt:66)
	at android.app.Activity.onMenuItemSelected(Activity.java:3545)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:218)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:6619)
	at android.view.View.performClickInternal(View.java:6596)
	at android.view.View.access$3100(View.java:780)
	at android.view.View$PerformClick.run(View.java:25951)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:879)
```

**Comment by rafaelekol** [comment]
By user words: "After phone reset issue resolved"
