### ISSUE TITLE
java.security.NosuchAlgorithException: error constructing implementation

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#3343]
device: Xiaomi Mi A1, Galaxy A20s
does not display any data

**Exception**

`java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: AndroidOpenSSL, class: com.android.org.conscrypt.DefaultSSLContextImpl)`

**Where**

`ApiManager::getJsonValue`

**URL**

`https://api.coingecko.com/api/v3/coins/markets?&vs_currency=USD&order=market_cap_desc&page=1&per_page=250`

**Comment by abdrasulov** [comment]
https://stackoverflow.com/questions/61352059/android-https-request-fails-weirdly

**Comment by abdrasulov** [comment]
There is no scenario to reproduce this issue. It occurs occasionally with no reason. There are similar issues posted on stackoverflow. Based on that posts I've decided to use okhttp instead of native java URL for making http requests.

**Comment by abdrasulov** [comment]
```
Caused by: java.lang.AssertionError: No System TLS: java.security.KeyManagementException: java.security.KeyStoreException: BKS not found
        at okhttp3.internal.platform.Platform.newSslSocketFactory(Platform.kt:163)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:238)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
        at io.horizontalsystems.xrateskit.api.ApiManager.<clinit>(ApiManager.kt:51)
        at io.horizontalsystems.xrateskit.providers.CoinPaprikaProvider.<init>(CoinPaprikaProvider.kt:12)
        at io.horizontalsystems.xrateskit.XRatesKit$Companion.create(XRatesKit.kt:128)
        at io.horizontalsystems.xrateskit.XRatesKit$Companion.create$default(XRatesKit.kt:122)
        at io.horizontalsystems.bankwallet.core.managers.RateManager$kit$2.invoke(RateManager.kt:29)
        at io.horizontalsystems.bankwallet.core.managers.RateManager$kit$2.invoke(RateManager.kt:20)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.horizontalsystems.bankwallet.core.managers.RateManager.getKit(Unknown Source:2)
        at io.horizontalsystems.bankwallet.core.managers.RateManager.onWalletsUpdated(RateManager.kt:141)
        at io.horizontalsystems.bankwallet.core.managers.RateManager.access$onWalletsUpdated(RateManager.kt:20)
        at io.horizontalsystems.bankwallet.core.managers.RateManager$1.accept(RateManager.kt:42)
        at io.horizontalsystems.bankwallet.core.managers.RateManager$1.accept(RateManager.kt:20)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.security.KeyManagementException: java.security.KeyStoreException: BKS not found
        at com.android.org.conscrypt.SSLParametersImpl.createDefaultX509KeyManager(SSLParametersImpl.java:468)
        at com.android.org.conscrypt.SSLParametersImpl.getDefaultX509KeyManager(SSLParametersImpl.java:449)
        at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java:124)
        at com.android.org.conscrypt.OpenSSLContextImpl.engineInit(OpenSSLContextImpl.java:103)
        at javax.net.ssl.SSLContext.init(SSLContext.java:316)
        at okhttp3.internal.platform.Platform.newSslSocketFactory(Platform.kt:160)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:238) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069) 
        at io.horizontalsystems.xrateskit.api.ApiManager.<clinit>(ApiManager.kt:51) 
        at io.horizontalsystems.xrateskit.providers.CoinPaprikaProvider.<init>(CoinPaprikaProvider.kt:12) 
        at io.horizontalsystems.xrateskit.XRatesKit$Companion.create(XRatesKit.kt:128) 
        at io.horizontalsystems.xrateskit.XRatesKit$Companion.create$default(XRatesKit.kt:122) 
        at io.horizontalsystems.bankwallet.core.managers.RateManager$kit$2.invoke(RateManager.kt:29) 
        at io.horizontalsystems.bankwallet.core.managers.RateManager$kit$2.invoke(RateManager.kt:20) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at io.horizontalsystems.bankwallet.core.managers.RateManager.getKit(Unknown Source:2)

```
