### ISSUE TITLE
Crash after secure storage prompt

### ISSUE THREAD

**Issue by thegergo02** [horizontalsystems/unstoppable-wallet-android#3648]
Hi!
This issue didn't arise after the 0.20.1 update, it was working fine for a while.
Phone: Huawei P10 Lite (WAS-LX1)
Android 8.0
EMUI 8.0
If I have the time I might try to read into the logs, maybe there are more useful informations there.

**Comment by thegergo02** [comment]
I found the error which gets triggered at the start (presumably that prompts me to authenticate) and then this gets logged after every authentication (which should be succesful as my phone indicates that):
```
2021-05-04 11:37:44.120 9926-9926/io.horizontalsystems.bankwallet.dev W/KeyStoreManager: isKeyInvalidated: 
     android.security.keystore.UserNotAuthenticatedException: User not authenticated
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:753)
        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:789)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2663)
        at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
        at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
        at javax.crypto.Cipher.init(Cipher.java:830)
        at javax.crypto.Cipher.init(Cipher.java:771)
        at io.horizontalsystems.core.security.CipherWrapper.encrypt(CipherWrapper.kt:18)
        at io.horizontalsystems.core.security.KeyStoreManager.validateKey(KeyStoreManager.kt:102)
        at io.horizontalsystems.core.security.KeyStoreManager.validateKeyStore(KeyStoreManager.kt:62)
        at io.horizontalsystems.bankwallet.modules.launcher.LaunchInteractor.validateKeyStore(LaunchInteractor.kt:40)
        at io.horizontalsystems.bankwallet.modules.launcher.LaunchPresenter.viewDidLoad(LaunchPresenter.kt:18)
        at io.horizontalsystems.bankwallet.modules.launcher.LaunchViewModel.init(LaunchViewModel.kt:21)
        at io.horizontalsystems.bankwallet.modules.launcher.LauncherActivity.onCreate(LauncherActivity.kt:32)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by thegergo02** [comment]
I had a feeling that the app properly implemented this, and it's a bug in the actual implementation of the KeyStoreManager on my phone, and I was fortunately correct. After restarting the phone the KeyStoreManager works and lets me into the application. Might be useful to indicate this after a few failed attempts?

**Comment by abdrasulov** [comment]
Hello @thegergo02,

Thanks for your detailed explanation. Yeah, the issue may be related to implementation of KeyStoreManger. Please, let us know if you face this issue again.
