### ISSUE TITLE
Room cannot verify the data integrity (branches: 0.22)

### ISSUE THREAD

**Issue by hoanghiephui** [horizontalsystems/unstoppable-wallet-android#3970]
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
        at io.horizontalsystems.ethereumkit.core.storage.TransactionSyncerStateDao_Impl.getTransactionSyncerState(TransactionSyncerStateDao_Impl.java:63)
        at io.horizontalsystems.ethereumkit.transactionsyncers.TransactionStorage.getTransactionSyncerState(TransactionStorage.kt:218)
        at io.horizontalsystems.ethereumkit.transactionsyncers.NotSyncedTransactionManager.getTransactionSyncerState(NotSyncedTransactionManager.kt:35)
        at io.horizontalsystems.ethereumkit.transactionsyncers.AbstractTransactionSyncer.getLastSyncBlockNumber(AbstractTransactionSyncer.kt:32)
        at io.horizontalsystems.erc20kit.core.Erc20TransactionSyncer.sync(Erc20TransactionSyncer.kt:30)
        at io.horizontalsystems.erc20kit.core.Erc20TransactionSyncer.start(Erc20TransactionSyncer.kt:16)
        at io.horizontalsystems.ethereumkit.transactionsyncers.TransactionSyncManager.add(TransactionSyncManager.kt:61)
        at io.horizontalsystems.ethereumkit.core.EthereumKit.addTransactionSyncer(EthereumKit.kt:271)
        at io.horizontalsystems.bankwallet.core.managers.EvmKitManager.createKitInstance(EvmKitManager.kt:115)
        at io.horizontalsystems.bankwallet.core.managers.EvmKitManager.evmKit(EvmKitManager.kt:91)
        at io.horizontalsystems.bankwallet.core.factories.AdapterFactory.ethereumTransactionsAdapter(AdapterFactory.kt:27)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.evmTransactionAdapter(AdapterManager.kt:146)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.initAdapters(AdapterManager.kt:112)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.preloadAdapters$lambda-4(AdapterManager.kt:96)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.lambda$v6cmxROUrWprn6FwwjA7H8UNghc(Unknown Source:0)

**Comment by rafaelekol** [comment]
Since this branch still in development stage we may not handle database migrations.
We had database changes in EthereumKit, but we didn't increase database version. 
You just need to clear app data, and restore your wallet with your keys.
