### ISSUE TITLE
Crash app when update to 0.22

### ISSUE THREAD

**Issue by hoanghiephui** [horizontalsystems/unstoppable-wallet-android#4051]
Fatal Exception: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
       at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
       at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
       at io.horizontalsystems.ethereumkit.core.storage.TransactionSyncerStateDao_Impl.getTransactionSyncerState(TransactionSyncerStateDao_Impl.java:63)
       at io.horizontalsystems.ethereumkit.transactionsyncers.TransactionStorage.getTransactionSyncerState(TransactionStorage.java:223)
       at io.horizontalsystems.ethereumkit.transactionsyncers.NotSyncedTransactionManager.getTransactionSyncerState(NotSyncedTransactionManager.java:35)
       at io.horizontalsystems.ethereumkit.transactionsyncers.AbstractTransactionSyncer.getLastSyncBlockNumber(AbstractTransactionSyncer.java:32)
       at io.horizontalsystems.erc20kit.core.Erc20TransactionSyncer.sync(Erc20TransactionSyncer.java:30)
       at io.horizontalsystems.erc20kit.core.Erc20TransactionSyncer.start(Erc20TransactionSyncer.java:16)
       at io.horizontalsystems.ethereumkit.transactionsyncers.TransactionSyncManager.add(TransactionSyncManager.java:61)
       at io.horizontalsystems.ethereumkit.core.EthereumKit.addTransactionSyncer(EthereumKit.java:268)
       at io.horizontalsystems.erc20kit.core.Erc20Kit$Companion.addTransactionSyncer(Erc20Kit.java:153)
       at io.horizontalsystems.bankwallet.core.managers.EvmKitManager.createKitInstance(EvmKitManager.java:111)
       at io.horizontalsystems.bankwallet.core.managers.EvmKitManager.evmKit(EvmKitManager.java:91)
       at io.horizontalsystems.bankwallet.core.factories.AdapterFactory.ethereumTransactionsAdapter(AdapterFactory.java:27)
       at io.horizontalsystems.bankwallet.core.managers.AdapterManager.evmTransactionAdapter(AdapterManager.java:146)
       at io.horizontalsystems.bankwallet.core.managers.AdapterManager.initAdapters(AdapterManager.java:112)
       at io.horizontalsystems.bankwallet.core.managers.AdapterManager.preloadAdapters$lambda-4(AdapterManager.java:96)
       at io.horizontalsystems.bankwallet.core.managers.AdapterManager.$r8$lambda$v6cmxROUrWprn6FwwjA7H8UNghc(AdapterManager.java)

**Comment by rafaelekol** [comment]
During sprint inside Version branch we may make changes to database tables without increasing version. But we make sure that migration should work in master branch for release builds. 
Did you install previous apk from Version branch?

**Comment by hoanghiephui** [comment]
> During sprint inside Version branch we may make changes to database tables without increasing version. But we make sure that migration should work in master branch for release builds.
> Did you install previous apk from Version branch?

I installed from master branchs

**Comment by rafaelekol** [comment]
I checked for same crash in PlayStore reports. There is no such crash for latest release. 
Can you reproduce the crash? And tell us when migration is not working.

**Comment by abdrasulov** [comment]
Most likely it was in dev version, not stable.
