### ISSUE TITLE
App crashes on Secure Folder powered by Samsung after 1 day

### ISSUE THREAD

**Issue by junzhli** [horizontalsystems/unstoppable-wallet-android#5515]
Hello team, I tried to use unstoppable wallet (shorthand as wl) under Secure Folder (Knox protected on Samsung phone)
It works well in the beginning of the time. After ~24hrs, I can't open wl again.
I looked into the adb logcat, and it is caused by the following error:

```
11-14 00:42:26.518 18144 18144 D AndroidRuntime: Shutting down VM
11-14 00:42:26.519 18144 18144 E AndroidRuntime: FATAL EXCEPTION: main
11-14 00:42:26.519 18144 18144 E AndroidRuntime: Process: io.horizontalsystems.bankwallet, PID: 18144
11-14 00:42:26.519 18144 18144 E AndroidRuntime: java.lang.IllegalStateException: No Colors provided
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at io.horizontalsystems.bankwallet.ui.compose.ThemeKt$LocalColors$1.invoke(Theme.kt:93)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at io.horizontalsystems.bankwallet.ui.compose.ThemeKt$LocalColors$1.invoke(Theme.kt:92)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.resolveCompositionLocal(Composer.kt:1969)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:1939)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at io.horizontalsystems.bankwallet.ui.compose.ComposeAppTheme.getColors(Theme.kt:96)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at io.horizontalsystems.bankwallet.modules.keystore.KeyStoreActivityKt$KeysInvalidatedDialog$1.invoke(KeyStoreActivity.kt:185)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at io.horizontalsystems.bankwallet.modules.keystore.KeyStoreActivityKt$KeysInvalidatedDialog$1.invoke(KeyStoreActivity.kt:180)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:163)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:162)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt.DialogLayout(AndroidDialog.android.kt:448)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt.access$DialogLayout(AndroidDialog.android.kt:1)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:160)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:157)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.window.DialogLayout.Content(AndroidDialog.android.kt:254)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:248)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:247)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3215)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:336)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3205)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3141)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:584)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:811)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3753)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1015)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1102)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:21976)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3469)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:797)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
11-14 00:42:26.519 18144 18144 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I also tried to reboot the phone and it can open but goes to clean state (just like clean cache/data, first-time launch time)
It starts to ask for wallet setup again. Not sure what's the root cause behind this.
Logcat log file attached here, thanks!
[logcat.log.zip](https://github.com/horizontalsystems/unstoppable-wallet-android/files/10018779/logcat.log.zip)

**Comment by junzhli** [comment]
App status page log after reboot attached here
[Log_221121_200028.txt](https://github.com/horizontalsystems/unstoppable-wallet-android/files/10057562/Log_221121_200028.txt)

**Comment by junzhli** [comment]
Hello @abdrasulov, I have a new finding and this may help, thanks
#5544

**Comment by junzhli** [comment]
Also, i think there's no further logging about nested exception in `InvalidKeyException`
I found this nested exception could know more about the reason behind this exception `android.security.KeyStoreException`
Refer to the similar problem:  [stackoverflow](https://stackoverflow.com/questions/42570020/invalidkeyexception-keystore-operation-failed-on-rsa-decrypt-on-android-device)

**Comment by junzhli** [comment]
Hello @abdrasulov 
Follow-up here:
I dive into the logcat log i attached the above, and there are some logs related to knox tee keystore operation failure
```
11-14 00:25:44.302  1122  2204 D DARUtil : is enterprise user : 150
11-14 00:25:44.306   692   692 W keymaster_tee: [WRN]begin req PARAMS: A32 B2 P64 
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (verify_authtoken_timeout:38) current_uptime(0x00000000053edc10) token_timestamp(0x000000000003335e) timeout 86400
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (verify_authtoken_timeout:39) Time is over
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (km_authtoken_matches:119) Invalid authorization timeout
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (km_verify_user_begin:279) km_authtoken_verify failed: -16
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (km_authorize_begin:281) Failed with error: 4294967
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (km_operation_init:341) Failed with error: 4294967
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [ERR] (swd_begin:437) Failed with error: 4294967
11-14 00:25:44.311   692   692 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:251) swd_begin() returns -16
11-14 00:25:44.311   692   692 W keymaster_tee: [WRN]Cmd 8, err -16
11-14 00:25:44.311   690   703 E keystore2/km_compat: !@ begin :  result = -16
11-14 00:25:44.311   690   703 E keystore2: keystore2::error: In create_operation: Failed to begin operation. 15011502
11-14 00:25:44.311   690   703 E keystore2: 
11-14 00:25:44.311   690   703 E keystore2: Caused by:
11-14 00:25:44.311   690   703 E keystore2:     0: In upgrade_keyblob_if_required_with: Called closure failed.
11-14 00:25:44.311   690   703 E keystore2:     1: Error::Km(ErrorCode(-16))
```
i think this is caused by the auth token timeout problem after 86400 secs defined under `AUTH_DURATION_SEC` i mentioned eariler. probably it needs to have a workaround here to handle specific error code from KeyStoreException, prompting user to ask for authentication again and have a retry for keystore validation rather than resetting app for this case

**Comment by junzhli** [comment]
Created a pr #5555 for fixing the crash on dialog prompting keystore invalidated
