### ISSUE TITLE
App crashes when all blockchain are enabled

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#5797]
2023-01-25 17:43:35.905 24905-25235/io.horizontalsystems.bankwallet.dev.appcenter E/AndroidRuntime: FATAL EXCEPTION: pool-20-thread-9
    Process: io.horizontalsystems.bankwallet.dev.appcenter, PID: 24905
    java.lang.OutOfMemoryError: Failed to allocate a 125960208 byte allocation with 25116672 free bytes and 89MB until OOM, target footprint 199511752, growth limit 268435456
        at io.horizontalsystems.bitcoincore.io.BitcoinInput.readBytes(BitcoinInput.java:217)
        at io.horizontalsystems.dashkit.models.Quorum.<init>(Quorum.kt:34)
        at io.horizontalsystems.dashkit.messages.MasternodeListDiffMessageParser.parseMessage(MasternodeListDiffMessage.kt:64)
        at io.horizontalsystems.bitcoincore.network.messages.NetworkMessageParser.parseMessage(IMessage.kt:52)
        at io.horizontalsystems.bitcoincore.network.peer.PeerConnection.run(PeerConnection.kt:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by abdrasulov** [comment]
Could not reproduce issue

**Comment by Dianaaiym** [comment]
duplicated #5887
