### ISSUE TITLE
java.util.NoSuchElementException app crashes when I switch on bitcon and kill and reopen the app

### ISSUE THREAD

**Issue by Amolak13** [horizontalsystems/unstoppable-wallet-android#6073]
Logs

Process: io.horizontalsystems.bankwallet.dev, PID: 17129
    java.util.NoSuchElementException
        at io.horizontalsystems.bitcoincore.managers.PublicKeyManager.gapKeysCount(PublicKeyManager.kt:183)
        at io.horizontalsystems.bitcoincore.managers.PublicKeyManager.fillGap(PublicKeyManager.kt:96)
        at io.horizontalsystems.bitcoincore.managers.PublicKeyManager.fillGap(PublicKeyManager.kt:64)
        at io.horizontalsystems.bitcoincore.managers.PublicKeyManager$Companion.create(PublicKeyManager.kt:132)
        at io.horizontalsystems.bitcoincore.BitcoinCoreBuilder.build(BitcoinCore.kt:175)
        at io.horizontalsystems.bitcoinkit.BitcoinKit.<init>(BitcoinKit.kt:177)
        at io.horizontalsystems.bitcoinkit.BitcoinKit.<init>(BitcoinKit.kt:99)
        at io.horizontalsystems.bitcoinkit.BitcoinKit.<init>(BitcoinKit.kt:76)
        at io.horizontalsystems.bitcoinkit.BitcoinKit.<init>(BitcoinKit.kt:66)
        at io.horizontalsystems.bankwallet.core.adapters.BitcoinAdapter$Companion.createKit(BitcoinAdapter.kt:111)
        at io.horizontalsystems.bankwallet.core.adapters.BitcoinAdapter$Companion.access$createKit(BitcoinAdapter.kt:88)
        at io.horizontalsystems.bankwallet.core.adapters.BitcoinAdapter.<init>(BitcoinAdapter.kt:28)
        at io.horizontalsystems.bankwallet.core.factories.AdapterFactory.getAdapter(AdapterFactory.kt:58)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.initAdapters(AdapterManager.kt:126)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.preloadAdapters$lambda$6(AdapterManager.kt:101)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager.$r8$lambda$AE8l_RtLsbCPqDX5025WzGkjIaE(Unknown Source:0)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by rafaelekol** [comment]
I can't reproduce this crash. I also searched for similar crash logs in Play Analytics and I didn't find it. Did you install from GooglePlay?

**Comment by Dianaaiym** [comment]
Could not reproduce the reported bug
