### ISSUE TITLE
App crash when marketkit get 404 on first connection

### ISSUE THREAD

**Issue by gades** [horizontalsystems/unstoppable-wallet-android#6632]
steps for reproduce:
1) please change marketApiBaseUrl to https://api-dev.blocksdecoded.com/11   (special wrong URL for fast reproduce)
2) create wallet if it's not created 
3) click to the BNB
4) click to the graphics 

here is log from app crash from wrong URL and it can be affected in case missing coin on blocksdecoded.

<-- 404 Not Found https://api-dev.blocksdecoded.com/11/v1/coins/binancecoin/price_chart_start (594ms, unknown-length body)
2023-09-22 16:48:44.549 10863-10941 AndroidRuntime          io.horizontalsystems.bankwallet.dev  E  FATAL EXCEPTION: DefaultDispatcher-worker-11
                                                                                                    Process: io.horizontalsystems.bankwallet.dev, PID: 10863
                                                                                                    retrofit2.adapter.rxjava2.HttpException: HTTP 404 Not Found
                                                                                                    	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
                                                                                                    	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
                                                                                                    	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at kotlinx.coroutines.rx2.RxAwaitKt.await(RxAwait.kt:139)
                                                                                                    	at io.horizontalsystems.bankwallet.modules.coin.overview.CoinOverviewChartService.start(CoinOverviewChartService.kt:49)
                                                                                                    	at io.horizontalsystems.bankwallet.modules.chart.ChartViewModel$5.invokeSuspend(ChartViewModel.kt:89)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@492ff85, Dispatchers.IO]
2023-09-22 16:48:44.572 10863-10941 Process                 io.horizontalsystems.bankwallet.dev  I  Sending signal. PID: 10863 SIG: 9

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by gades** [comment]
@rafaelekol Could you please lock comments for this issue because it's fixed but there a lot of links to viruses ?
