### ISSUE TITLE
Gradle obfuscation crashes the tinder-scarlet in startup

### ISSUE THREAD

**Issue by MohammadFakhraee** [horizontalsystems/unstoppable-wallet-android#7405]
I know this might be an irrelevant issue. But as Tinder Scarlet library is not being updated and you are using this library, so you might face the issue which I couldn't solve.

With gradle version above 8, there is a weird issue with obfuscation. I am trying to run the scarlet demo app when enabling obfuscation with `minifyEnabled true` but it crashes with the following message:

```
java.lang.IllegalArgumentException: Receive method must return ParameterizedType: public abstract kotlinx.coroutines.flow.Flow com.tinder.app.echo.api.EchoService.observeBitmap()
          at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(ServiceMethod.kt:100)
          at com.tinder.scarlet.internal.servicemethod.ServiceMethod$Receive$Factory.create(ServiceMethod.kt:66)
          at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.toServiceMethod(ServiceMethodExecutor.kt:47)
          at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.findServiceMethods(ServiceMethodExecutor.kt:38)
          at com.tinder.scarlet.internal.servicemethod.ServiceMethodExecutor$Factory.create(ServiceMethodExecutor.kt:32)
          at com.tinder.scarlet.internal.Service$Factory.create(Service.kt:28)
          at com.tinder.scarlet.Scarlet.implementService(Scarlet.kt:108)
          at com.tinder.scarlet.Scarlet.create(Scarlet.kt:100)
          at com.tinder.app.echo.inject.EchoBotComponent$EchoBotModule.provideEchoService(EchoBotComponent.kt:105)
```

The problem is when the demo is not minifying, the methods of scarlet service interfaces has a `genericReturnType` of `ParameterizedTypeImpl` type. But when switching `minifyingEnabled` on, the `genericReturnType` will become a type of `java.lang.Class`.

**Comment by Dianaaiym** [comment]
Closing as outdated. Please reopen if this is still relevant.
