### ISSUE TITLE
App crashed on Transactions Page during Sync

### ISSUE THREAD

**Issue by rafaelekol** [horizontalsystems/unstoppable-wallet-android#974]
Crash Log:

```
Process: io.horizontalsystems.bankwallet.dev, PID: 15351
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=6
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:385)
        at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:398)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionItemDataSource.itemForIndex(TransactionItemDataSource.kt:23)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionRecordDataSource.itemForIndex(TransactionRecordDataSource.kt:27)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsLoader.itemForIndex(TransactionsLoader.kt:26)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsPresenter.itemForIndex(TransactionsPresenter.kt:44)
        at io.horizontalsystems.bankwallet.modules.transactions.TransactionsAdapter.onBindViewHolder(TransactionsFragment.kt:167)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6937)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6979)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5896)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6163)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6002)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5998)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2226)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4033)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3750)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4303)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:144)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:41)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1687)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:898)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:20831)
        at android.view.ViewGroup.layout(ViewGroup.java:6203)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:20831)
```

**Comment by omurovch** [comment]
The issue is already implemented and no longer relevant
